# Generated by Django 3.2.6 on 2021-09-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210905_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
